### ISSUE TITLE
proposal for a pull request

### ISSUE THREAD

**Issue by steenzout** [tskirvin/omdclient#12]
@tskirvin, would you be interested in:
- adding travis-ci.org integration?
- adding readthedocs.org integration?
- adding a way to automatically publish this client to pip main repo so people could to `pip install omdclient`

I can make pull requests to do all of the above if you are interested.

lmk.

PS: great work on this tool.

**Comment by tskirvin** [comment]
I'd be interested, sure!

**Comment by steenzout** [comment]
I'll start working on that then.
