### ISSUE TITLE
Expanded views

### ISSUE THREAD

**Issue by epleterte** [tskirvin/omdclient#3]
Hey,

the client seems to rely on 'expanded views', i.e. `hostproblems_expanded` and `svcproblems_expanded`. These are not default views - how does one go about setting them up?

Some hints/instructions about this in the docs would be cool :)

**Comment by epleterte** [comment]
So what I ended up doing was this:

Edit a view like `hostproblems` - it's one of the default views, so you'll automatically be taken to "Clone" the view (instead of editing). Change the name from `hostproblems` to `hostproblems_expanded`, then go down to the list of columns and add one more: "Host comments". Do the same for `serviceproblems` (and add column "Service comments".

**Comment by epleterte** [comment]
...did I miss something, or is this the expected way/easiest way of getting those expanded views? I'd be happy to provide a pull request with this added to the documentation (unless you prefer doing it yourself :) ).

**Comment by tskirvin** [comment]
This is pretty much the best way to do it.  I'll put your docs into the README.  Thanks for bugging me on this, I should have gotten to it earlier!
